name: Deploy Laravel Project

on:
  push:
    branches: [ main ] 

jobs:
  web-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: ⚡️ Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4' 

      - name: 📥 Install Composer Dependencies
        run: composer install --no-ansi --no-dev --no-interaction --no-plugins --no-progress --no-scripts --optimize-autoloader

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '25.9.0' 

      - name: 🔨 Build Assets (Vite)
        run: |
          npm install
          npm run build
      
      - name: 🗑️ Remove heavy folders before sync
        run: |
          rm -rf vendor
          rm -rf node_modules
          

      - name: 📂 Sync Files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          
          server-dir: domains/pelabuhanlembarsejahtera.co.id/public_html/
          port: 21
          
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/tests/**
            .env.example
            phpunit.xml
            storage/
            vendor/
            .env